[workspace]
resolver = "2"
members = [
    "uncflow-agent",
    "uncflow-raw",
]

[workspace.package]
version = "2.0.0"
edition = "2021"
authors = ["Minhu Wang <minhuw@acm.org>"]
license = "MIT"
repository = "https://github.com/minhuw/uncflow"

[workspace.dependencies]
thiserror = "2.0.17"
